# 第二个注册中心
server:
    port: 8088
# 与peer2节点同步数据
peer2:
    server:
        host: localhost
        port: 18088
# 配置eureka注册中心数据同步
eureka:
    client:
        # 连接集群中另外地注册中心
        service-url:
            defaultZone: http://${peer2.server.host}:${peer2.server.port}/eureka
management:
    port: 9009