server:
    port: 8093
management:
    port: 9014
    security:
        enabled: false
spring:
    application:
        name: spring-cloud-zipkin-sleuth
    cloud:
        stream:
            rabbit:
                binder:
                    adminAddresses: 192.168.43.2,192.168.43.3,192.168.43.4
                    nodes: 192.168.43.2,192.168.43.3,192.168.43.4
    rabbitmq:
        addresses: 192.168.43.2,192.168.43.3,192.168.43.4
        username: admin
        password: 123456