server:
    port: 8084
management:
    security:
        enabled: false
    port: 9005
spring:
    application:
        name: "spring-cloud-eureka-client"
# 配置注册中心地址
eureka:
    instance:
        # 配置状态检查页面地址(使用绝对地址,默认是/info)
        status-page-url: http://localhost:8084/status
        # 配置健康检查页面地址(使用相对地址,默认是/health)
        health-check-url-path: /health
user:
    nickname: xuebaochai
    age: 18