# web服务器端口
server:
    port: 8888
endpoints:
    restart:
        # 开启端点
        enabled: true
        # 关闭安全
        sensitive: false
management:
    security:
        enabled: false
    port: 9001

