server:
    port: 8086
management:
    port: 9007
    security:
        enabled: false
spring:
    application:
        name: spring-cloud-consul-client
# 接入consul
    cloud:
        consul:
            host: localhost
            port: 8500
