# 开发环境使用命令行参数模拟多个注册中心启动
server:
    port: 8083
spring:
    application:
        name: spring-cloud-eureka-server
management:
    security:
        enabled: false
    port: 9004
# 配置eureka注册中心
eureka:
    instance:
        #com.netflix.eureka.cluster.PeerEurekaNodes.isInstanceURL方法中
        #String myInfoComparator = instance.getHostName();获取自定义hostname
        #如果不配置,会随着运行机器不同而经常改变(默认规则)
        hostname: localhost
    client:
        # 注册中心本身不需要作为客户端注册到其他eureka注册中心
        register-with-eureka: false
        # 不需要从注册中心获取客户端信息(服务/实例信息)
        fetch-registry: false
        # 自己作为自己的副本,防止集群副本连接8761端口报错(当前cloud版本必须这样写)
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka