# 第二个客户端实例
server:
    port: 18087
management:
    port: 19008
# 配置注册中心地址
eureka:
    client:
        service-url:
            # 多个注册中心使用逗号分隔
            defaultZone: http://localhost:8088/eureka/,http://localhost:18088/eureka/
        # 从注册中心获取所有客户端配置信息地间隔时间
        registry-fetch-interval-seconds: 5
        # 客户端副本改变信息通知eureka服务器
        instance-info-replication-interval-seconds: 5
spring:
    application:
        name: cloud-client-eureka-high-available