server:
    port: 8081
endpoints:
    restart:
        enabled: true
        sensitive: false
management:
    security:
        enabled: false
    port: 9002
spring:
    application:
        name: "spring-cloud-config-client"
user:
    nickname: baoyatou
    age: 16
