server:
    port: 8090
management:
    port: 9011
    security:
        enabled: false
spring:
    application:
        name: spring-cloud-user-server
    cloud:
        stream:
            # 设置默认binder
            default-binder: activemq
            # 激活Spring Cloud Stream Binding(激活@StreamListener)
            bindings:
                active-message:
                    destination: activemq-test
                    # 名称来自于META-INF/spring.factories
                    binder: activemq
    activemq:
        broker-url: tcp://localhost:61616
    jms:
        template:
            default-destination: activemq-test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8083/eureka/
        registry-fetch-interval-seconds: 15
        # 引入eureka客户端依赖后,临时关闭eureka客户端功能
        #enabled: false

