server:
    port: 8090
management:
    port: 9011
    security:
        enabled: false
spring:
    application:
        name: spring-cloud-user-server
    kafka:
        # 集群地址
        bootstrap-servers: 192.168.43.2:9092,192.168.43.3:9092,192.168.43.4:9092
        producer:
            acks: 1
            client-id: lx-spring-cloud-stream-producer1
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.liangxiong.server.provider.component.ObjectSerializer
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8083/eureka/
        registry-fetch-interval-seconds: 15
        # 引入eureka客户端依赖后,临时关闭eureka客户端功能
        #enabled: false

