server:
    port: 8085
management:
    security:
        enabled: false
    port: 9006
spring:
    application:
        name: spring-cloud-config-server-as-client-for-eureka
    cloud:
        config:
            # 配置中心相关配置
            server:
                git:
                    # 配置远程Github仓库地址
                    uri: https://github.com/liangxiong3403/temp
                    # 强制拉取远程仓库文件内容(Flag to indicate that the repository should force pull. If true discard any local changes and take from remote repository.)
                    force-pull: true
            discovery:
                # 配置服务发现
                enabled: true
                service-id: spring-cloud-config-server-as-client-for-eureka
eureka:
    client:
        # 配置eureka注册中心地址
        service-url:
            defaultZone: http://127.0.0.1:8083/eureka/